# Generated by Django 3.2.3 on 2024-02-28 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='video_files/')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('processing', models.BooleanField(default=False)),
                ('processingSuccess', models.BooleanField(null=True)),
            ],
        ),
    ]
